name: 'Update'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 */2 * * *'
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Update'
        run: echo $(cat /proc/sys/kernel/random/uuid) > UUID.txt
      - name: 'Commit Files'
        id: commit
        run: |
          git config --local user.email "97015005+sbsony@users.noreply.github.com"
          git config --local user.name "sbsony"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am 'Update'
          echo ::set-output name=status::success    
      - name: 'GitHub Push'
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
